<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU9xwbpj\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU9xwbpj/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerU9xwbpj.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerU9xwbpj\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerU9xwbpj\appProdProjectContainer([
    'container.build_hash' => 'U9xwbpj',
    'container.build_id' => 'd2c525a8',
    'container.build_time' => 1649037017,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU9xwbpj');
